#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  keyboard:
    layout: us

  identity:
    hostname: lerix-node
    username: lerix
    password: "$6$tSX3J8Oo4ZILqRCW$OS8ZR2.AZDi/AkbNmkc3VvJ0oith1zZ7eHetPR8oukUNtCdFpFi9814Kl2VJrZB5bUzwbKZedfrikDYhl1CAX0"

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - docker.io
    - pciutils
    - ubuntu-drivers-common

  storage:
    swap:
      size: 0
    config:
      - type: disk
        id: disk0
        match:
          ssd: true
          size: largest
        ptable: gpt
        wipe: superblock-recursive
        grub_device: true

      - type: partition
        id: part-efi
        device: disk0
        size: 512M
        flag: boot
      - type: format
        id: fs-efi
        volume: part-efi
        fstype: fat32
      - type: mount
        id: mnt-efi
        device: fs-efi
        path: /boot/efi

      - type: partition
        id: part-root
        device: disk0
        size: 60G
      - type: format
        id: fs-root
        volume: part-root
        fstype: ext4
      - type: mount
        id: mnt-root
        device: fs-root
        path: /

      - type: partition
        id: part-docker
        device: disk0
        size: 60G
      - type: format
        id: fs-docker
        volume: part-docker
        fstype: ext4
      - type: mount
        id: mnt-docker
        device: fs-docker
        path: /var/lib/docker

      - type: partition
        id: part-data
        device: disk0
        size: -1
      - type: format
        id: fs-data
        volume: part-data
        fstype: ext4
      - type: mount
        id: mnt-data
        device: fs-data
        path: /data

  late-commands:
    - curtin in-target -- bash -lc 'set -eux; systemctl enable docker.service containerd.service; systemctl restart docker.service'
    - curtin in-target -- bash -lc 'set -eux; if lspci | grep -qi nvidia; then ubuntu-drivers install; fi'
    - |
      cat > /target/etc/profile.d/90-gpu-docker-info.sh <<'SCRIPT'
      #!/usr/bin/env bash
      [ -t 1 ] || return 0

      if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then
        gpu_msg="NVIDIA GPU detected"
      else
        gpu_msg="NVIDIA GPU not detected"
      fi

      if systemctl is-active --quiet docker; then
        docker_msg="Docker service: active"
      else
        docker_msg="Docker service: inactive"
      fi

      printf '\n[INFO] %s | %s\n\n' "$gpu_msg" "$docker_msg"
      SCRIPT
    - chmod 0755 /target/etc/profile.d/90-gpu-docker-info.sh

  shutdown: reboot
